apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: support
  description: TOM Support group
spec:
  type: sub-department
  profile:
    displayName: Support
    email: support@tompay.com.tr
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: tom-it-dept
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ali.tutebilir
spec:
  profile:
    # Intentional no displayName for testing
    email: ali.tutebilir@tompay.com.tr
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [support]
